baseURL = 'https://keyhankamyar.github.io/'
theme = 'PaperMod'
languageCode = 'en-us'
title = 'Keyhan Kamyar'

[params]
  defaultTheme = 'dark'        # force dark by default
  disableThemeToggle = false   # keep the toggle if visitors want light
  ShowReadingTime = true
