baseURL = 'https://keyhankamyar.github.io/'
theme = 'PaperMod'
languageCode = 'en-us'
title = 'Keyhan Kamyar'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
copyright = "© 2025 Keyhan Kamyar"

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "Keyhan Kamyar"
  description = "ML Engineer & Researcher specializing in Deep RL, Financial AI, and High-Performance Computing. Building systems that learn, adapt, and perform under uncertainty."
  keywords = ["Machine Learning", "Reinforcement Learning", "Deep RL", "ML Engineering", "PyTorch", "Quant", "Financial AI", "Algorithmic Trading", "High Performance Computing", "Python", "MLOps"]
  author = "Keyhan Kamyar"
  images = ["/images/social-card.png"]
  
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.profileMode]
    enabled = true
    title = "Keyhan Kamyar"
    subtitle = "ML Engineer & Researcher"
    imageUrl = ""
    imageWidth = 120
    imageHeight = 120
    imageTitle = ""
    
    [[params.profileMode.buttons]]
      name = "Projects"
      url = "/projects"
    
    [[params.profileMode.buttons]]
      name = "Blog"
      url = "/posts"
    
    [[params.profileMode.buttons]]
      name = "About"
      url = "/about"

  [params.homeInfoParams]
    Title = ""
    Content = ""

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/keyhankamyar"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/keyhan-kamyar/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:keyhankamyar@gmail.com"

  [params.cover]
    linkFullImages = true
    responsiveImages = true

[params.assets]
  disableHLJS = false
  disableFingerprinting = false
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 20

[[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/posts/"
  weight = 30

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4


[params.schema]
  publisherType = "Person"
  sameAs = [
    "https://github.com/keyhankamyar",
    "https://www.linkedin.com/in/keyhan-kamyar/",
    "https://keyhankamyar.github.io"
  ]


[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]
